export const CREATE_USER = "CREATE_USER";
export const CREATE_ROOM_RESPONSE = 'CREATE_ROOM_RESPONSE';
export const CREATE_ROOM = "CREATE_ROOM";
export const ADD_USER_TO_ROOM = "ADD_USER_TO_ROOM";
export const NEW_USER = "NEW_USER";
export const NEW_USER_RESPONSE = "NEW_USER_RESPONSE";